### ISSUE TITLE
core.clj: Implement future-call

### ISSUE THREAD

**Issue by dmiller** [richhickey/clojure-clr#16]
Depends on clojure.lang.Agent/soloExecutor (need to implement), but more worryingly on java.util.concurrent.Future. The CTP concurrency runtime has this, or we implement.

**Comment by dmiller** [comment]
The concurrency runtime appears to have been withdrawn.  Someone besides me needs to implement Future.

**Comment by jolson88** [comment]
Yeah, Future<T> (now Task<T>) was withdrawn because it is now part of .NET Framework 4.0 (integrated directly into System.dll and mscorlib).

Since it will obviously be a while before clojure-clr can take a dependency on .NET Framework 4, an alternate option is to use the Joins Concurrency Library from Microsoft Research (it is used by both Polyphonic C# and COmega). The Joins library has a sample for Future<T> and some other cool stuff as well.

Download here: http://research.microsoft.com/en-us/downloads/f9d6994e-45f6-49b8-b3c9-2a44bb2a4c50/default.aspx.

**Comment by shoover** [comment]
For the record, I have a patch pending with David for future-call.

**Comment by dmiller** [comment]
Issued moved to assembla.
